services:
  back-end:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      data-base:
        condition: service_healthy
      redis:
        condition: service_healthy

  data-base:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: paodepovilho2003
      POSTGRES_USER: postgres
      POSTGRES_DB: desafio-angular-api
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d desafio-angular-api" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge