!========== database config =============!
spring.datasource.url=jdbc:postgresql://localhost:5432/desafio-angular-api
spring.datasource.username=postgres
spring.datasource.password=desafiosipel2026

!========== cache config =============!
spring.data.redis.host=localhost
